configs:
  # Configuration principale ArgoCD
  cm:
    # Comptes API
    accounts.readonly: apiKey
    # Status badge
    statusbadge.enabled: true
    statusbadge.url: "https://argocd-badge.wheezy.fr/"

    # Configuration OIDC
    oidc.config: |
      name: Authentik
      issuer: https://auth.wheezy.fr/application/o/argo-cd/
      clientID: mda1YuKv8TyyTG8ozm62BcLsXc6R2bfrM2f6NBBi
      clientSecret: $oidc.authentik.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
      requestedIDTokenClaims:
        groups:
          essential: true

  # Configuration RBAC
  rbac:
    policy.default: role:readonly
    policy.csv: |
      # Compte API readonly
      g, readonly, role:readonly

      # Groupes Authentik - Admins
      g, authentik Admins, role:admin
      g, argocd-admins, role:admin

      # Groupes Authentik - Developers
      g, argocd-developers, role:developer

      # Définition du rôle developer
      p, role:developer, applications, *, */*, allow
      p, role:developer, repositories, *, *, allow
      p, role:developer, projects, get, *, allow
      p, role:developer, clusters, get, *, allow
      p, role:developer, certificates, get, *, allow
      p, role:developer, logs, get, *, allow

    scopes: "[groups, email]"

  # Paramètres ArgoCD
  params:
    server.insecure: true
    server.repo.server.plaintext: true
    controller.repo.server.plaintext: true
    applicationsetcontroller.repo.server.plaintext: true
    reposerver.disable.tls: true

# Dex désactivé
dex:
  enabled: false

# Configuration du serveur ArgoCD
server:
  ingress:
    enabled: true
    tls: true
