ipam:
  mode: "kubernetes"

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - CAP_BPF
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: "/sys/fs/cgroup"

k8sService:
  host: "localhost"
  port: "7445"

kubeProxyReplacement: true
l2announcements:
  enabled: true

devices: "{eth0}"

ingressController:
  enabled: true
  default: true
  loadbalancerMode: "shared"
  enforceHttps: false

gatewayAPI:
  enabled: true
  enableProxyProtocol: true
  gatewayClass:
    create: "true"
  hostNetwork:
    enabled: true
  enableAlpn: true
  enableAppProtocol: true
  xffNumTrustedHops: 1
  externalTrafficPolicy: "Cluster"
  secretsNamespace:
    name: "cilium-secrets"
    sync: true

envoy:
  enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  dashboards:
    enabled: true
    namespace: "observability"
  serviceMonitor:
    enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction

prometheus:
  enabled: true

operator:
  prometheus:
    enabled: true
