name: Terraform Init

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-init:
    name: Run Terraform Init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Terraform Init
        run: terraform init
